
Backend API using Java

@backend_url = https://auth-workshop-user6-backend.azurewebsites.net
###

###
POST {{backend_url}}/api/v1/todos
content-type: application/json

{
    "title": "伝票処理",
    "task": "空港に荷物をおくる",
    "duedate": "2022-10-20" ,
    "status": "Pending"
}

###
GET {{backend_url}}/api/v1/todos

###
PUT {{backend_url}}/api/v1/todos/1
content-type: application/json

{
    "title": "発送処理",
    "task": "羽田空港から発送する",
    "duedate": "2022-10-25" ,
    "status": "Pending"
}

###
DELETE {{backend_url}}/api/v1/todos/2



###
GET {{backend_url}}/.auth/me

