
Backend API using Java

###
POST https://auth-workshop-user1-backend.azurewebsites.net/api/v1/todos HTTP/1.1
content-type: application/json

{
    "title": "伝票処理",
    "task": "空港に荷物をおくる",
    "duedate": "2022-10-20" ,
    "status": "Pending"
}


###
GET https://auth-workshop-user1-backend.azurewebsites.net/api/v1/todos HTTP/1.1
content-type: application/json


###
POST https://auth-workshop-user1-backend.azurewebsites.net/api/v1/todos HTTP/1.1
content-type: application/json

{
    "title": "伝票処理",
    "task": "空港に荷物をおくる",
    "duedate": "2022-10-20" ,
    "status": "Pending"
}


###
PUT https://auth-workshop-user1-backend.azurewebsites.net/api/v1/todos/1 HTTP/1.1
content-type: application/json

{
    "title": "発送処理",
    "task": "羽田空港から発送する",
    "duedate": "2022-10-25" ,
    "status": "Pending"
}

